name: json_object
version: 1.0.18
author: Chris Buckett <chrisbuckett@gmail.com>
description: Allow use of JSON Maps in dot notation format
homepage: https://github.com/chrisbu/dartwatch-JsonObject
environment:
  sdk: '>=0.6.0+1.r24898'
dev_dependencies:
  unittest: '>=0.6.0+1'
